// Code generated by tygo. DO NOT EDIT.
// ⚠️ 此文件由 tygo 从后端 internal/schema/types.go 自动生成
// 禁止手动编辑！修改后端类型后请运行 `make sync-types`

//////////
// source: types.go
/*
Package schema defines all data contracts flowing between Agents.
This file is the SINGLE SOURCE OF TRUTH — tygo generates frontend TS types from it.
Run `make sync-types` after any change here.
*/

/**
 * AgentStatus is the runtime state of an Agent in the DAG.
 * Mirrors the frontend status color encoding (see frontend docs/styling-guide.md).
 */
export type AgentStatus = string;
export const AgentStatusPending: AgentStatus = "pending";
export const AgentStatusRunning: AgentStatus = "running";
export const AgentStatusReview: AgentStatus = "review";
export const AgentStatusError: AgentStatus = "error";
export const AgentStatusDone: AgentStatus = "done";
/**
 * UserQuery 用户输入请求
 */
export interface UserQuery {
  competitor_name: string;
  target_url: string;
  dimensions: string[]; // pricing / feature / tech / market
  priority: number /* int */; // 1-5
  requested_by: string;
}
/**
 * TaskDAGPlan Orchestrator 输出的任务执行计划
 */
export interface TaskDAGPlan {
  task_id: string;
  competitor_name: string;
  dimensions: string[];
  requires_web_scrape: boolean;
  requires_social: boolean;
  requires_financial: boolean;
  requires_review: boolean;
  requires_api: boolean;
  target_schema: string;
  created_at: string;
  expires_at: string;
}
/**
 * RawDataPack 采集器原始输出
 */
export interface RawDataPack {
  task_id: string;
  source_type: string; // web / social / financial / review / api
  source_url: string;
  raw_content: string;
  headers: { [key: string]: string};
  status_code: number /* int */;
  captured_at: string;
  collector_id: string;
  fingerprint: string; // SHA-256 of raw content
}
/**
 * NormalizedDataset Cleaner 清洗后输出
 */
export interface NormalizedDataset {
  task_id: string;
  viking_uri: string;
  source_type: string;
  cleaned_text: string;
  structured: { [key: string]: any};
  sim_hash_value: number /* uint64 */;
  confidence: number /* float64 */;
  cleaned_at: string;
  cleaner_id: string;
}
/**
 * AnalysisResult 分析师输出
 */
export interface AnalysisResult {
  task_id: string;
  dimension: string; // pricing / feature / tech / market
  payload: string;
  cot_reason: string;
  score: number /* float64 */; // confidence 0-1
  source_uris: string[];
  analyzer_id: string;
  model_name: string;
  analyzed_at: string;
}
/**
 * ReviewReport 交叉审查输出
 */
export interface ReviewReport {
  task_id: string;
  is_approved: boolean;
  conflicts: Conflict[];
  analyses: (AnalysisResult | undefined)[]; // forwarded from analyzers for writer
  next_action: string; // APPROVE / RETRY_AUTO / REJECT_HUMAN
  reviewed_at: string;
  reviewer_id: string;
  debate_rounds: number /* int */;
}
/**
 * Conflict 单条冲突描述
 */
export interface Conflict {
  dimension: string;
  agent_ids: string[];
  description: string;
  severity: string; // low / medium / high
  suggested_fix: string;
}
/**
 * DraftReport 撰写员输出
 */
export interface DraftReport {
  task_id: string;
  title: string;
  markdown_content: string;
  footnotes: Footnote[];
  merkle_root_hash: string;
  confidence: number /* float64 */;
  generated_at: string;
  writer_id: string;
}
/**
 * Footnote 溯源脚注
 */
export interface Footnote {
  id: string;
  conclusion: string;
  confidence: number /* float64 */;
  provenance_id: string;
  viking_uri: string;
}
/**
 * FinalReviewInput 终审员输入
 */
export interface FinalReviewInput {
  task_id: string;
  report_id: string;
  content: string;
  merkle_root_hash: string;
  confidence: number /* float64 */;
  generated_at: string;
}
/**
 * FinalReviewOutput 终审员输出
 */
export interface FinalReviewOutput {
  report_id: string;
  content: string;
  status: string; // APPROVED / REJECTED / NEEDS_REVISION
  signature: string;
  comment: string;
  approved_at: string;
  approved_by: string;
}
/**
 * FinalReport 系统最终输出
 */
export interface FinalReport {
  task_id: string;
  report_id: string;
  content: string;
  status: string; // published / draft / rejected
  signature: string;
  approved_by: string;
  approved_at: string;
  merkle_root: string;
  footnotes: Footnote[];
}
/**
 * Competitor 竞品实体
 */
export interface Competitor {
  uid?: string;
  company_name?: string;
  founded_date?: string;
  funding_stage?: string;
  headquarters?: string;
  team_size?: number /* int */;
  threat_level?: number /* int */;
  website?: string;
  competes_with?: (Competitor | undefined)[];
  develops?: (Product | undefined)[];
}
/**
 * Feature 功能实体
 */
export interface Feature {
  uid?: string;
  availability?: boolean;
  category?: string;
  description?: string;
  evidence_url?: string;
  feature_name?: string;
  last_updated?: string;
  maturity?: number /* int */;
  part_of?: Product;
}
/**
 * MarketEvent 市场事件实体
 */
export interface MarketEvent {
  uid?: string;
  confidence?: number /* float64 */;
  description?: string;
  event_date?: string;
  event_type?: string;
  impact?: string;
  source_url?: string;
}
/**
 * PricingTier 定价实体
 */
export interface PricingTier {
  uid?: string;
  billing_model?: string;
  currency?: string;
  last_updated?: string;
  limitations?: string;
  price?: number /* float64 */;
  target_segment?: string;
  tier_name?: string;
}
/**
 * Product 产品实体
 */
export interface Product {
  uid?: string;
  category?: string;
  core_tech?: string;
  description?: string;
  launch_date?: string;
  product_name?: string;
  review_count?: number /* int */;
  user_rating?: number /* float64 */;
  belongs_to?: Competitor;
  has_pricing?: (PricingTier | undefined)[];
  offers_feature?: (Feature | undefined)[];
}
/**
 * TechComponent 技术栈实体
 */
export interface TechComponent {
  uid?: string;
  architecture?: string;
  component_name?: string;
  github_stars?: number /* int */;
  last_commit?: string;
  open_source?: boolean;
  technology?: string;
}
/**
 * UserSegment 用户群体实体
 */
export interface UserSegment {
  uid?: string;
  core_pain_points?: string[];
  description?: string;
  satisfaction_score?: number /* float64 */;
  segment_name?: string;
  typical_use_cases?: string[];
}
